experiment_name: "EffNv2S_head"
seed: 42

data:
  train_dir: "data/train"
  val_dir: "data/val"
  image_size: 384
  batch_size: 64
  num_workers: 2
  pin_memory: true
  weighted_sampling: false
  max_weight: 5
  
model:
  backbone: "tf_efficientnetv2_s" # e.g. "tf_efficientnetv2_s"  "convnextv2_tiny.fcmae_ft_in22k_in1k_384"  eva02_base_patch14_224 
  pretrained: true
  freeze_backbone: true
  freeze_bn: true
  num_classes: null # Inferred automatically from dataset
  dropout: 0.2
  drop_path: 0.1

loss:
  name: "ce" # "focal" or "ce"
  gamma: 2.0
  alpha: 0.25
  label_smoothing: 0.1

optimizer:
  name: "adamw"
  backbone_lr: 0 #dont matter if layer_decay 
  head_lr: 5e-4 
  weight_decay: 1e-2
  layer_decay: 1.0
  
scheduler:
  name: "step" # "cosine", "step", "plateau"
  warmup_epochs: 0
  min_lr: 0.0

training:
  epochs: 10
  gradient_accumulation_steps: 1
  mixed_precision: true
  clip_grad_norm: 1.0
  early_stopping_patience: 5
  ema:
    enabled: true
    decay: 0.9995
    eval_mode: "current" # "current" or "ema"
  
augmentation:
  mixup_alpha: 0.2
  cutmix_alpha: 0.5
  prob: 0 # Probability applied per batch

logging:
  use_wandb: true
  project_name: "plant-disease-classification"
  checkpoint_dir: "./checkpoints"
